### ISSUE TITLE
Troubleshooting Lycophron installation and uploads — celery

### ISSUE THREAD

**Issue by juwingert** [plazi/lycophron#45]
# Summary
I've been trying to get Lycophron to work on Windows 11. Upon investigation, I found a solution that involved using 3 terminals (one to run celery worker, one for celery beat and another for lycophron proper).
Once I got through it, I got a .db file with TODOs for the listed files, but it doesn't progress beyond that.

## Installing
Here's a rundown of the steps I did to finish my installation of Lycophron:

Steps to run Lycophron by Windows:

***Terminal 1: Start Celery Worker**
`$env:LYCOPHRON_CONFIG = "C:\Users\wingert_plazi\odonte\.lycophron\config.toml"
$env:CELERY_BROKER_URL = "redis://localhost:6379/0"
$env:CELERY_RESULT_BACKEND = "redis://localhost:6379/0"
& "$env:USERPROFILE\pipx\venvs\lycophron\Scripts\celery.exe" -A lycophron.tasks worker --loglevel=info --pool=solo
`
<img width="1097" height="385" alt="Image" src="https://github.com/user-attachments/assets/2777feb1-42d2-48eb-9f71-62d29fff9b9e" />

***Terminal 2: Start Celery Beat**
`$env:LYCOPHRON_CONFIG = "C:\Users\wingert_plazi\odonte\.lycophron\config.toml"
& "$env:USERPROFILE\pipx\venvs\lycophron\Scripts\celery.exe" -A lycophron.tasks beat --loglevel=info
`
<img width="1090" height="504" alt="Image" src="https://github.com/user-attachments/assets/9150c81d-80e0-4153-8c2e-40031550d899" />

***Terminal 3: Queue Records for Publishing**
`cd C:\Users\wingert_plazi\odonte
`
<img width="675" height="450" alt="Image" src="https://github.com/user-attachments/assets/6b9bf6a4-08f9-4e79-be2e-8843222da1f9" />
<img width="1092" height="178" alt="Image" src="https://github.com/user-attachments/assets/5db39333-4ad0-4615-a702-0931dc1a8637" />
<img width="1098" height="160" alt="Image" src="https://github.com/user-attachments/assets/d9295d66-964e-45e6-a9a0-c197e1543c97" />

*I had to create another file to replace lycophron.cfg, it's .toml:
 [zenodo]
access_token = "I put my token"
sandbox = true

[celery]
broker_url = "redis://localhost:6379/0"
result_backend = "redis://localhost:6379/0"

*Lycophron load my spreadsheet (in attached)
*I stopped when it generated the status as TODO in the .DB file

<img width="1402" height="632" alt="Image" src="https://github.com/user-attachments/assets/40f016e4-417b-4622-8850-10263a9c8227" />

## Example spreadsheet
This is the spreadsheet I used for my upload attempt
[LycophronOdontesthesTemplate2.csv](https://github.com/user-attachments/files/21059554/LycophronOdontesthesTemplate2.csv)

**Comment by slint** [comment]
The corrected CSV import file is:

[input_fixed.csv](https://github.com/user-attachments/files/21578966/input_fixed.csv)

Changes made (some of which Lycophron should validate)

- The community was changed from "BLR" to `biosyslit`
- `access.files` should be either empty (for open access) or `restricted` for closed access
- `creators.name` should be empty if `creators.family_name`
  - For institutions/organizations it should have a value and `creators.family_name` and `creators.given_name` should be empty
- ORCiD was fixed (but this should be Lycohpron validating)
- `contributors.role.id` was set to `datacurator` (full list of valid values at https://sandbox.zenodo.org/api/vocabularies/creatorsroles?size=100)
  - ~~:warning: requires a fix in Lycophron code for it work.~~ fix has been pushed
- Communities not included (even though configured correctly)

**Comment by juwingert** [comment]
Hi @slint , now we find the following error:

[export.csv](https://github.com/user-attachments/files/21583182/export.csv)

I have already changed the token, but the error persists.

**Comment by flsimoes** [comment]
@slint 

It seems that, in order to run Lycophron in Windows (PowerShell) you'll need to add/define celery to the base installation of lycophron
Otherwise, any user will have to go through the hassle of running celery and lycophron in a virtual environment, with both `beat` and `worker` running on separate instances of powershell

**Comment by flsimoes** [comment]
I managed to make lycophron run on Linux (Raspbian GNU/Linux 11)

The test uploads are all in sandbox. However, I get this never ending string of records being dispatched. Not sure what's going on, so i killed the process after some time running it. By the way, there's a typo in record-dispathcer

<img width="3840" height="2160" alt="Image" src="https://github.com/user-attachments/assets/1bb3a7a3-790d-4786-b25a-4703ccf71f57" />

**Comment by slint** [comment]
> It seems that, in order to run Lycophron in Windows (PowerShell) you'll need to add/define celery to the base installation of lycophron Otherwise, any user will have to go through the hassle of running celery and lycophron in a virtual environment, with both `beat` and `worker` running on separate instances of powershell

I found a workaround for this actually that will make it possible to run Lycophron on Windows as well. AFAIK, on fresh Windows 11 setup, I only had to [install `uv`](https://docs.astral.sh/uv/getting-started/installation/#standalone-installer) and [`git`](https://git-scm.com/downloads/win) (which was needed for the `uv tool install "..."` installation command to work for GitHub).

I'll push this fix (along with the others that were discussed) and update the documenation.

**Comment by slint** [comment]
FYI, I've fixed the issue with the Windows installation, so upgrading `lycophron` with `uv tool upgrade lycophron` should result in a working installation on Windows, where running `lycophron start` will not crash and actually start uploading records to Zenodo.

I'm testing the fix for adding the records to the community, and after that I think the only improvements from https://github.com/plazi/lycophron/issues/45#issuecomment-3150844788 left are for better validation error messages and overall guidance.

**Comment by juwingert** [comment]
@slint Hi, Thank you for your update. The last week, I was able to upload two of the five articles before this last update. 

<img width="1161" height="901" alt="Image" src="https://github.com/user-attachments/assets/ed4e359d-a9e6-4be6-8ceb-cc9e097fb6ff" />

Today I upgraded Lycophron and tried to upload the other three, but I get the following error:

<img width="1103" height="258" alt="Image" src="https://github.com/user-attachments/assets/418a8e91-a53b-4f9d-96c2-57fe40b4cf9c" />
<img width="1102" height="253" alt="Image" src="https://github.com/user-attachments/assets/dd3bc14a-130a-4f75-8c76-11007a40164e" />

However, it continues to run without updating in Sandbox.

**Comment by juwingert** [comment]
I tried more two papers:

<img width="1119" height="271" alt="Image" src="https://github.com/user-attachments/assets/1d24da72-d914-4e0a-8458-d2434abac249" />
<img width="1106" height="475" alt="Image" src="https://github.com/user-attachments/assets/bd68e975-df8e-494d-8cde-34c364f4f157" />
<img width="1090" height="468" alt="Image" src="https://github.com/user-attachments/assets/53c5f30f-5c6f-4c3e-abc2-2f6729b62c93" />
<img width="1087" height="503" alt="Image" src="https://github.com/user-attachments/assets/6b09493a-0a06-4ae8-a5f3-9d4408c6e81e" />
<img width="1092" height="463" alt="Image" src="https://github.com/user-attachments/assets/9f334355-5b9b-47a1-8039-96c2368f36df" />
<img width="1125" height="392" alt="Image" src="https://github.com/user-attachments/assets/b9be915a-3f8b-4906-928f-6266004eb714" />

**Comment by ptamarit** [comment]
@juwingert sorry for the late reply.

> I tried more two papers:

1. As you showed in your screenshot, the first record went through: https://sandbox.zenodo.org/records/332555
2. Concerning the second record, it seems that there was a connection problem when uploading the file, because when going to https://sandbox.zenodo.org/uploads/332557 we can see that the file is pending. In such cases, one currently needs to go to the user interface and delete the pending file manually. After this, re-uploading the file via Lycophron should work.

**Comment by juwingert** [comment]
@ptamarit thanks for your reply, I'll do this and check if resolve that.

**Comment by juwingert** [comment]
Hi dear @ptamarit , I ran a test and managed to upload a paper! Thanks for the feedback.

On the other hand, we are testing with images. I ran a test yesterday and uploaded 3 images; they are in the Zenodo sandbox showing the red "incomplete" icon (first image), yet they show 100% progress (second image). 

<img width="486" height="538" alt="Image" src="https://github.com/user-attachments/assets/ba90aa95-0333-43a4-9aad-e5c6c8337cd5" />

<img width="1037" height="373" alt="Image" src="https://github.com/user-attachments/assets/9cff54a2-792b-42df-b3fa-7b54644d7e63" />

Could you please explain to me what is happening? I'm sending you the log file.

[dev_logs.log](https://github.com/user-attachments/files/32253558/dev_logs.log)

Thanks, cheers.

**Comment by ptamarit** [comment]
@juwingert Going to:
* https://sandbox.zenodo.org/uploads/603108
* https://sandbox.zenodo.org/uploads/603110
* https://sandbox.zenodo.org/uploads/603112

And clicking on the "Preview" button, I can see that 2 mandatory fields are missing:
* Basic information > Publication date
* Recommended information > Publisher

I believe this is why the records did not go all the way through publication.
Definitely something that should be validated or shown back to Lycophron users instead of a generic error (sorry about this).

**Comment by juwingert** [comment]
Dear @ptamarit I got it, thanks for your feedback. Cheers
